import { jsPDF } from 'jspdf';

type ReportValue = string | number | null | undefined;

export interface EngineeringReportInput {
  project: Record<string, ReportValue>;
  climate: Record<string, ReportValue>;
  materials: Record<string, ReportValue>;
  userDesign: Record<string, ReportValue>;
  aiDesign: Record<string, ReportValue>;
  userAnalysis: Record<string, ReportValue>;
  aiAnalysis: Record<string, ReportValue>;
  userCost: Record<string, ReportValue>;
  aiCost: Record<string, ReportValue>;
  mlPrediction: Record<string, ReportValue> | null;
  comparison: Array<[string, ReportValue, ReportValue, ReportValue]>;
  hourlyTemperatures: number[];
  dataSource: string;
  modelInformation: Record<string, ReportValue>;
}

const unavailable = (value: ReportValue) => value === null || value === undefined || value === '' ? 'Not available' : String(value);
const numberText = (value: ReportValue, digits = 1, unit = '') => {
  if (typeof value !== 'number' || !Number.isFinite(value)) return 'Not available';
  return `${value.toFixed(digits)}${unit ? ` ${unit}` : ''}`;
};
const inr = (value: ReportValue) => typeof value === 'number' && Number.isFinite(value)
  ? `INR ${Math.round(value).toLocaleString('en-IN')}` : 'Not available';

export function downloadEngineeringReport(input: EngineeringReportInput): void {
  const pdf = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = 210;
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  let cursor = 22;

  const footer = () => {
    pdf.setDrawColor(213, 224, 220);
    pdf.line(margin, 285, pageWidth - margin, 285);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8);
    pdf.setTextColor(95, 112, 107);
    pdf.text('AASHRAYA GANITH | Climate-Adaptive Passive Shelter Intelligence', margin, 291);
    pdf.text(`Page ${pdf.getNumberOfPages()}`, pageWidth - margin, 291, { align: 'right' });
  };
  const ensureSpace = (height: number) => {
    if (cursor + height > 277) {
      footer();
      pdf.addPage();
      cursor = 22;
    }
  };
  const title = (text: string) => {
    ensureSpace(14);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(15);
    pdf.setTextColor(8, 127, 106);
    pdf.text(text, margin, cursor);
    cursor += 8;
  };
  const paragraph = (text: string) => {
    const lines = pdf.splitTextToSize(text, contentWidth) as string[];
    ensureSpace(lines.length * 5 + 4);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(9.5);
    pdf.setTextColor(40, 57, 53);
    pdf.text(lines, margin, cursor);
    cursor += lines.length * 5 + 4;
  };
  const table = (headers: string[], rows: string[][]) => {
    const widths = headers.length === 4 ? [52, 43, 43, 36] : [62, contentWidth - 62];
    const rowHeight = 7;
    ensureSpace((rows.length + 1) * rowHeight + 5);
    const drawRow = (values: string[], header = false) => {
      let x = margin;
      values.forEach((value, index) => {
        const width = widths[index] ?? contentWidth / values.length;
        const fillColor: [number, number, number] = header ? [8, 127, 106] : [247, 250, 249];
        pdf.setFillColor(...fillColor);
        pdf.setDrawColor(213, 224, 220);
        pdf.rect(x, cursor, width, rowHeight, 'FD');
        pdf.setFont('helvetica', header ? 'bold' : 'normal');
        pdf.setFontSize(7.5);
        const textColor: [number, number, number] = header ? [255, 255, 255] : [40, 57, 53];
        pdf.setTextColor(...textColor);
        pdf.text(pdf.splitTextToSize(value, width - 3) as string[], x + 1.5, cursor + 4.5);
        x += width;
      });
      cursor += rowHeight;
    };
    drawRow(headers, true);
    rows.forEach(row => drawRow(row));
    cursor += 4;
  };
  const keyValueSection = (heading: string, values: Record<string, ReportValue>) => {
    title(heading);
    table(['Parameter', 'Value'], Object.entries(values).map(([key, value]) => [key, unavailable(value)]));
  };

  pdf.setFillColor(8, 127, 106);
  pdf.rect(0, 0, pageWidth, 8, 'F');
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(27);
  pdf.setTextColor(24, 49, 45);
  pdf.text('AASHRAYA GANITH', margin, 58);
  pdf.setFontSize(16);
  pdf.setTextColor(8, 127, 106);
  pdf.text('Climate-Adaptive Passive Shelter Intelligence', margin, 69);
  pdf.setFontSize(13);
  pdf.setTextColor(60, 78, 73);
  pdf.text('Engineering Analysis & AI Optimization Report', margin, 80);
  pdf.setDrawColor(32, 168, 138);
  pdf.line(margin, 90, pageWidth - margin, 90);
  pdf.setFontSize(10);
  pdf.setTextColor(95, 112, 107);
  pdf.text(`Generated ${unavailable(input.project['Generated date'])}`, margin, 101);
  pdf.text(`Project: ${unavailable(input.project['Location'])}`, margin, 108);
  paragraph('This report presents the current shelter requirements, climate inputs, thermal model outputs, material profile, cost estimate and engineering comparison generated by the AASHRAYA GANITH application. It is based on the analysis state at the time of download.');
  footer();
  pdf.addPage();
  cursor = 22;

  title('1. Executive Summary');
  paragraph(`The project evaluates a ${unavailable(input.project['Shelter purpose'])} for ${unavailable(input.project['Occupants'])}. The selected requirement is ${unavailable(input.project['Area'])} and the analysis location is ${unavailable(input.project['Location'])}. The AI-optimized engineering logic estimates an indoor peak of ${numberText(input.aiAnalysis['Peak indoor temperature'], 1, 'deg C')} versus ${numberText(input.userAnalysis['Peak indoor temperature'], 1, 'deg C')} for the user-defined design, with a thermal score of ${unavailable(input.aiAnalysis['Thermal score'])}/100. The optimization is a transparent passive-design logic layer; ML prediction, when available, is used for thermal and environmental prediction only.`);
  keyValueSection('2. Project Requirements', input.project);
  keyValueSection('3. Climate Input & Conditions', { ...input.climate, 'Data source status': input.dataSource });
  keyValueSection('4. ML Prediction', input.mlPrediction ?? { Status: 'Not available' });
  keyValueSection('5. Material Profile', input.materials);
  keyValueSection('6. User-Defined Design', input.userDesign);
  keyValueSection('7. AI-Optimized Design', input.aiDesign);

  title('8. User Design vs AI Design Comparison');
  table(['Parameter', 'User Design', 'AI-Optimized', 'Difference / Improvement'], input.comparison.map(row => row.map(unavailable)));

  keyValueSection('9. Thermal Analysis', input.aiAnalysis);
  keyValueSection('10. Solar Analysis', {
    'Solar radiation': input.climate['Solar radiation'],
    'Incident solar energy': input.aiAnalysis['Incident solar energy'],
    'Estimated absorbed heat gain': input.aiAnalysis['Solar thermal energy'],
    'Roof area': input.aiAnalysis['Roof area'],
    'Peak sun hours': input.climate['Peak sun hours']
  });
  keyValueSection('11. Heat Flow Analysis', {
    'AI roof heat flow': input.aiAnalysis['Roof heat flow'],
    'AI wall heat flow': input.aiAnalysis['Wall heat flow'],
    'AI opening heat flow': input.aiAnalysis['Opening heat flow'],
    'AI total heat flow': input.aiAnalysis['Total heat flow'],
    'User total heat flow': input.userAnalysis['Total heat flow'],
    'Period transfer': input.aiAnalysis['Period heat transfer']
  });
  keyValueSection('12. Airflow / Ventilation Analysis', {
    'Air exchange index, user': input.userAnalysis['Air exchange index'],
    'Air exchange index, AI': input.aiAnalysis['Air exchange index'],
    'Ventilation strategy': input.aiDesign['Ventilation']
  });
  keyValueSection('13. Cost Analysis', {
    'User design estimated cost': inr(input.userCost['Total']),
    'AI design estimated cost': inr(input.aiCost['Total']),
    'Cost difference': typeof input.aiCost['Total'] === 'number' && typeof input.userCost['Total'] === 'number' ? inr(input.aiCost['Total'] - input.userCost['Total']) : 'Not available',
    'AI materials estimate': inr(input.aiCost['Materials']),
    'AI labour estimate': inr(input.aiCost['Labour']),
    'Available budget': inr(input.project['Budget'])
  });

  title('14. Passive Design Strategy');
  paragraph(`The current design represents passive measures supported by the application: ${unavailable(input.materials['Insulation'])} insulation, ${unavailable(input.materials['Roof material'])} roofing, a ${unavailable(input.aiDesign['Shade depth'])} shading strategy, ${unavailable(input.aiDesign['Ventilation'])} ventilation, and the selected wall and floor materials. The model estimates their combined effect through solar protection, ventilation and thermal-mass terms.`);
  title('15. Engineering Interpretation');
  paragraph(`The AI-optimized design is expected to improve thermal protection through the displayed changes in wall thickness, roof pitch, shading and ventilation. The comparison should be read as a model-based engineering estimate: a lower peak indoor temperature, higher thermal score, lower absorbed solar gain or lower heat flow indicates improved passive performance within this analysis. Cost implications are shown as calculated estimates and should be reviewed against quantities, local rates and constructability.`);
  title('16. Final Recommendation');
  paragraph(`Use the AI-optimized design as the recommended concept for further engineering development, subject to review of the selected ${unavailable(input.materials['Wall material'])} wall, ${unavailable(input.materials['Roof material'])} roof, ${unavailable(input.materials['Insulation'])} insulation and ${unavailable(input.materials['Floor material'])} floor profile. Its principal reported benefit is a predicted indoor peak of ${numberText(input.aiAnalysis['Peak indoor temperature'], 1, 'deg C')} and thermal score ${unavailable(input.aiAnalysis['Thermal score'])}/100. Confirm site measurements, structural details, drainage, openings and local construction rates before implementation.`);
  title('17. Limitations & Disclaimer');
  paragraph('Results are engineering estimates and simulation outputs from the current application. Weather conditions vary, and model predictions depend on the available data and supplied inputs. Live, manual, fallback or synthetic data status is identified where exposed by the application. Site-specific measurements can improve accuracy. This report is not a substitute for final structural, civil, architectural, fire, safety or statutory approval.');
  keyValueSection('18. Report Data / Model Information', input.modelInformation);
  if (input.hourlyTemperatures.length) {
    title('19. Analysis Period Temperature Series');
    table(['Hour', 'Ambient temperature'], input.hourlyTemperatures.map((temperature, hour) => [String(hour).padStart(2, '0') + ':00', numberText(temperature, 1, 'deg C')]));
  }

  footer();
  const date = new Date().toISOString().slice(0, 10);
  pdf.save(`AASHRAYA_GANITH_Engineering_Report_${date}.pdf`);
}